auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9095

common:
  path_prefix: /loki  # Define um diretório comum para o compactor e outros componentes

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 15m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache  # Cache location for boltdb-shipper
  filesystem:
    directory: /loki/chunks  # Directory for storing chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false  # Desativa metadados estruturados para evitar o erro do schema

chunk_store_config: {}

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

compactor:
  working_directory: /loki/compactor  # Define um diretório de trabalho para o compactor
